source 'https://rubygems.org'

gem "rails", "~> 4.2.10"
gem "pg", "~> 0.19.0"
gem "rake", "~> 10.5.0"
gem "beforehand", path: '../../'
gem "sidekiq", "~> 5.2"
gem "redis", "~> 4.0"
gem "redis-rails", "~> 4.0"

